// Generated by view binder compiler. Do not edit!
package com.example.cameraxapp.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.ProgressBar;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.cameraxapp.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityGraphBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ImageView imageViewCombinedGraph;

  @NonNull
  public final ProgressBar progressBarGraphImage;

  @NonNull
  public final TextView textViewGraphStatus;

  private ActivityGraphBinding(@NonNull ConstraintLayout rootView,
      @NonNull ImageView imageViewCombinedGraph, @NonNull ProgressBar progressBarGraphImage,
      @NonNull TextView textViewGraphStatus) {
    this.rootView = rootView;
    this.imageViewCombinedGraph = imageViewCombinedGraph;
    this.progressBarGraphImage = progressBarGraphImage;
    this.textViewGraphStatus = textViewGraphStatus;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityGraphBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityGraphBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_graph, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityGraphBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.imageViewCombinedGraph;
      ImageView imageViewCombinedGraph = ViewBindings.findChildViewById(rootView, id);
      if (imageViewCombinedGraph == null) {
        break missingId;
      }

      id = R.id.progressBarGraphImage;
      ProgressBar progressBarGraphImage = ViewBindings.findChildViewById(rootView, id);
      if (progressBarGraphImage == null) {
        break missingId;
      }

      id = R.id.textViewGraphStatus;
      TextView textViewGraphStatus = ViewBindings.findChildViewById(rootView, id);
      if (textViewGraphStatus == null) {
        break missingId;
      }

      return new ActivityGraphBinding((ConstraintLayout) rootView, imageViewCombinedGraph,
          progressBarGraphImage, textViewGraphStatus);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
