// Generated by data binding compiler. Do not edit!
package com.example.cameraxapp.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.Switch;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.camera.view.PreviewView;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.databinding.DataBindingUtil;
import androidx.databinding.ViewDataBinding;
import com.example.cameraxapp.R;
import java.lang.Deprecated;
import java.lang.Object;

public abstract class ActivityPantallaCamaraBinding extends ViewDataBinding {
  @NonNull
  public final Button button;

  @NonNull
  public final ConstraintLayout main;

  @NonNull
  public final ImageView processedImageView;

  @NonNull
  public final Switch switch1;

  @NonNull
  public final TextView textViewRelativeX;

  @NonNull
  public final TextView textViewRelativeY;

  @NonNull
  public final PreviewView viewFinder;

  protected ActivityPantallaCamaraBinding(Object _bindingComponent, View _root,
      int _localFieldCount, Button button, ConstraintLayout main, ImageView processedImageView,
      Switch switch1, TextView textViewRelativeX, TextView textViewRelativeY,
      PreviewView viewFinder) {
    super(_bindingComponent, _root, _localFieldCount);
    this.button = button;
    this.main = main;
    this.processedImageView = processedImageView;
    this.switch1 = switch1;
    this.textViewRelativeX = textViewRelativeX;
    this.textViewRelativeY = textViewRelativeY;
    this.viewFinder = viewFinder;
  }

  @NonNull
  public static ActivityPantallaCamaraBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup root, boolean attachToRoot) {
    return inflate(inflater, root, attachToRoot, DataBindingUtil.getDefaultComponent());
  }

  /**
   * This method receives DataBindingComponent instance as type Object instead of
   * type DataBindingComponent to avoid causing too many compilation errors if
   * compilation fails for another reason.
   * https://issuetracker.google.com/issues/116541301
   * @Deprecated Use DataBindingUtil.inflate(inflater, R.layout.activity_pantalla_camara, root, attachToRoot, component)
   */
  @NonNull
  @Deprecated
  public static ActivityPantallaCamaraBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup root, boolean attachToRoot, @Nullable Object component) {
    return ViewDataBinding.<ActivityPantallaCamaraBinding>inflateInternal(inflater, R.layout.activity_pantalla_camara, root, attachToRoot, component);
  }

  @NonNull
  public static ActivityPantallaCamaraBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, DataBindingUtil.getDefaultComponent());
  }

  /**
   * This method receives DataBindingComponent instance as type Object instead of
   * type DataBindingComponent to avoid causing too many compilation errors if
   * compilation fails for another reason.
   * https://issuetracker.google.com/issues/116541301
   * @Deprecated Use DataBindingUtil.inflate(inflater, R.layout.activity_pantalla_camara, null, false, component)
   */
  @NonNull
  @Deprecated
  public static ActivityPantallaCamaraBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable Object component) {
    return ViewDataBinding.<ActivityPantallaCamaraBinding>inflateInternal(inflater, R.layout.activity_pantalla_camara, null, false, component);
  }

  public static ActivityPantallaCamaraBinding bind(@NonNull View view) {
    return bind(view, DataBindingUtil.getDefaultComponent());
  }

  /**
   * This method receives DataBindingComponent instance as type Object instead of
   * type DataBindingComponent to avoid causing too many compilation errors if
   * compilation fails for another reason.
   * https://issuetracker.google.com/issues/116541301
   * @Deprecated Use DataBindingUtil.bind(view, component)
   */
  @Deprecated
  public static ActivityPantallaCamaraBinding bind(@NonNull View view, @Nullable Object component) {
    return (ActivityPantallaCamaraBinding)bind(component, view, R.layout.activity_pantalla_camara);
  }
}
