// Generated by view binder compiler. Do not edit!
package com.example.cameraxapp.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.cameraxapp.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ListItemRecordingBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final TextView textViewRecordingName;

  @NonNull
  public final TextView textViewRecordingTimestamp;

  private ListItemRecordingBinding(@NonNull LinearLayout rootView,
      @NonNull TextView textViewRecordingName, @NonNull TextView textViewRecordingTimestamp) {
    this.rootView = rootView;
    this.textViewRecordingName = textViewRecordingName;
    this.textViewRecordingTimestamp = textViewRecordingTimestamp;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ListItemRecordingBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ListItemRecordingBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.list_item_recording, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ListItemRecordingBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.textViewRecordingName;
      TextView textViewRecordingName = ViewBindings.findChildViewById(rootView, id);
      if (textViewRecordingName == null) {
        break missingId;
      }

      id = R.id.textViewRecordingTimestamp;
      TextView textViewRecordingTimestamp = ViewBindings.findChildViewById(rootView, id);
      if (textViewRecordingTimestamp == null) {
        break missingId;
      }

      return new ListItemRecordingBinding((LinearLayout) rootView, textViewRecordingName,
          textViewRecordingTimestamp);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
